scrape_task:
  description: >
    Search for {product_name} on multiple e-commerce websites and scrape all product prices.
    This includes Amazon, Flipkart, Walmart, BestBuy, eBay, Target, and AliExpress.
  expected_output: >
    A JSON dictionary with store names and respective prices for {product_name} from all available sources.
  agent: product_scraper


compare_task:
  description: >
    Compare all collected product prices and determine the lowest price available.
  expected_output: >
    A report showing the best price and the store offering it for {product_name}.
  agent: price_comparator

notify_task:
  description: >
    Send an alert to the user when the best price for {product_name} is found.
  expected_output: >
    An email or notification alerting the user about the best available price for {product_name}.
  agent: notifier
