scrape_task:
  description: >
    Search for {product_name} on multiple e-commerce websites and scrape 
    all relevant details (prices, ratings, shipping info, etc.).
  expected_output: >
    A JSON-like structure containing store names, prices, ratings, 
    and any other relevant attributes for {product_name}.
  agent: product_scraper

compare_task:
  description: >
    Compare all collected product information based on {decision_criterion}. 
    Possible criteria: cost, rating, shipping_speed, brand_reputation, etc.
  expected_output: >
    A structured report identifying the best option for {product_name} 
    given the {decision_criterion}. For instance:
    {
      "best_store": "...",
      "best_price": "...", 
      "best_rating": "...",
      ...
    }
  agent: price_comparator

notify_task:
  description: >
    Notify the user about the selected best product according to the 
    provided {decision_criterion}.
  expected_output: >
    A clear notification or message stating the chosen store, 
    the relevant details, and why it is best based on {decision_criterion}.
  agent: notifier
